# A Google Container Engine (GKE) deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sibyl-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sibyl
    spec:

      volumes:
        - name: sibyl-nginx-configmap
          configMap:
            name: nginx-sse
        - name: sibyl-gcloud-key-file
          secret:
            secretName: gcloud-key-file
            defaultMode: 256

      containers:
          
        # Nginx web server
        - name: sibyl-nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sibyl-nginx-configmap
              mountPath: /etc/nginx/conf.d/
              
        # Sibyl app server
        - name: sibyl-server
          image: stencila/sibyl-server
          imagePullPolicy: Always
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375
            - name: SIBYL_CLUSTER
              value: 'true'
            - name: SIBYL_FROM
              value: stencila/alpha
            - name: SIBYL_REGISTRY
              value: gcr.io/stenci.la/api-project-72315317623
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: token-secret.txt
            - name: BETA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: beta-token
                  key: beta-token.txt
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: sibyl-gcloud-key-file
              mountPath: /mnt/secrets

        # Docker-in-Docker (dind) to build bundle images
        - name: sibyl-docker
          image: docker:dind
          securityContext:
            privileged: true
          ports:
            - containerPort: 2375

---

# Auto-scale the Sibyl deployment

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sibyl-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: sibyl-deployment
  minReplicas: 1
  maxReplicas: 1

---

# Expose the Sibyl server

kind: Service
apiVersion: v1
metadata:
  name: sibyl-service
spec:
  type: NodePort
  selector:
    app: sibyl
  ports:
    - name: http
      protocol: TCP
      port: 80

---

# Provide a cluster ingress

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sibyl-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sibyl
spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: sibyl-service
            servicePort: 80
